name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: build xcframework
      run: make xcframework
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: products/libzcashlc.xcframework.zip
    
